CREATE TABLE IF NOT EXISTS roles (
    id SMALLINT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMPTZ
);

INSERT INTO roles (id, name, created_at, updated_at) VALUES
  (1, 'superadmin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'admin',      CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'user',       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;